/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppMilitaresRouteImport } from './routes/app.militares'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppFeriasRouteImport } from './routes/app.ferias'
import { Route as AppEscalasRouteImport } from './routes/app.escalas'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAssinaturasRouteImport } from './routes/app.assinaturas'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as ApiAsaasCreateCheckoutRouteImport } from './routes/api.asaas.create-checkout'
import { Route as ApiPublicWebhooksNexanoRouteImport } from './routes/api.public.webhooks.nexano'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppMilitaresRoute = AppMilitaresRouteImport.update({
  id: '/militares',
  path: '/militares',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppFeriasRoute = AppFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasRoute = AppEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturasRoute = AppAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const ApiAsaasCreateCheckoutRoute = ApiAsaasCreateCheckoutRouteImport.update({
  id: '/api/asaas/create-checkout',
  path: '/api/asaas/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNexanoRoute = ApiPublicWebhooksNexanoRouteImport.update({
  id: '/api/public/webhooks/nexano',
  path: '/api/public/webhooks/nexano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/militares': typeof AppMilitaresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/api/asaas/create-checkout': typeof ApiAsaasCreateCheckoutRoute
  '/api/public/webhooks/nexano': typeof ApiPublicWebhooksNexanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/militares': typeof AppMilitaresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/api/asaas/create-checkout': typeof ApiAsaasCreateCheckoutRoute
  '/api/public/webhooks/nexano': typeof ApiPublicWebhooksNexanoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/assinaturas': typeof AppAssinaturasRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/ferias': typeof AppFeriasRoute
  '/app/importar': typeof AppImportarRoute
  '/app/militares': typeof AppMilitaresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/api/asaas/create-checkout': typeof ApiAsaasCreateCheckoutRoute
  '/api/public/webhooks/nexano': typeof ApiPublicWebhooksNexanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/app'
    | '/auth'
    | '/redefinir-senha'
    | '/app/assinatura'
    | '/app/assinaturas'
    | '/app/auditoria'
    | '/app/escalas'
    | '/app/ferias'
    | '/app/importar'
    | '/app/militares'
    | '/app/usuarios'
    | '/app/'
    | '/api/asaas/create-checkout'
    | '/api/public/webhooks/nexano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando'
    | '/auth'
    | '/redefinir-senha'
    | '/app/assinatura'
    | '/app/assinaturas'
    | '/app/auditoria'
    | '/app/escalas'
    | '/app/ferias'
    | '/app/importar'
    | '/app/militares'
    | '/app/usuarios'
    | '/app'
    | '/api/asaas/create-checkout'
    | '/api/public/webhooks/nexano'
  id:
    | '__root__'
    | '/'
    | '/aguardando'
    | '/app'
    | '/auth'
    | '/redefinir-senha'
    | '/app/assinatura'
    | '/app/assinaturas'
    | '/app/auditoria'
    | '/app/escalas'
    | '/app/ferias'
    | '/app/importar'
    | '/app/militares'
    | '/app/usuarios'
    | '/app/'
    | '/api/asaas/create-checkout'
    | '/api/public/webhooks/nexano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguardandoRoute: typeof AguardandoRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiAsaasCreateCheckoutRoute: typeof ApiAsaasCreateCheckoutRoute
  ApiPublicWebhooksNexanoRoute: typeof ApiPublicWebhooksNexanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/militares': {
      id: '/app/militares'
      path: '/militares'
      fullPath: '/app/militares'
      preLoaderRoute: typeof AppMilitaresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ferias': {
      id: '/app/ferias'
      path: '/ferias'
      fullPath: '/app/ferias'
      preLoaderRoute: typeof AppFeriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escalas': {
      id: '/app/escalas'
      path: '/escalas'
      fullPath: '/app/escalas'
      preLoaderRoute: typeof AppEscalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinaturas': {
      id: '/app/assinaturas'
      path: '/assinaturas'
      fullPath: '/app/assinaturas'
      preLoaderRoute: typeof AppAssinaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/asaas/create-checkout': {
      id: '/api/asaas/create-checkout'
      path: '/api/asaas/create-checkout'
      fullPath: '/api/asaas/create-checkout'
      preLoaderRoute: typeof ApiAsaasCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nexano': {
      id: '/api/public/webhooks/nexano'
      path: '/api/public/webhooks/nexano'
      fullPath: '/api/public/webhooks/nexano'
      preLoaderRoute: typeof ApiPublicWebhooksNexanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppAssinaturasRoute: typeof AppAssinaturasRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppEscalasRoute: typeof AppEscalasRoute
  AppFeriasRoute: typeof AppFeriasRoute
  AppImportarRoute: typeof AppImportarRoute
  AppMilitaresRoute: typeof AppMilitaresRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppAssinaturasRoute: AppAssinaturasRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppEscalasRoute: AppEscalasRoute,
  AppFeriasRoute: AppFeriasRoute,
  AppImportarRoute: AppImportarRoute,
  AppMilitaresRoute: AppMilitaresRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguardandoRoute: AguardandoRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiAsaasCreateCheckoutRoute: ApiAsaasCreateCheckoutRoute,
  ApiPublicWebhooksNexanoRoute: ApiPublicWebhooksNexanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
